sudo: required

language: cpp


matrix:
  include:
    - os: linux
      name: "Static analysis"
      env: STATIC_ANALYSIS=ON
      before_install:
        - |
          if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
            curl -L http://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format-diff.py -o $TRAVIS_BUILD_DIR/script/clang-format-diff.py;
          fi
      script:
        - cd ${TRAVIS_BUILD_DIR}
        - |
          if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
            echo "Checking clang-format between TRAVIS_BRANCH=$TRAVIS_BRANCH and TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH"
            bash $TRAVIS_BUILD_DIR/script/check_code_format.sh
          else
            echo "Skipping clang-format check since this is not a pull request."
          fi
