name: test-clang-format
  
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.6
      with:
        # Source folder to check formatting
        source: src/
        extensions: cpp,h
        # Version of clang-format
        clangFormatVersion: 9
